cmd_/home/bloink/Work/unnamedlinuxdistro/linux/tools/objtool/libstring.o := gcc -Wp,-MD,/home/bloink/Work/unnamedlinuxdistro/linux/tools/objtool/.libstring.o.d -Wp,-MT,/home/bloink/Work/unnamedlinuxdistro/linux/tools/objtool/libstring.o -std=gnu11 -fomit-frame-pointer -O2 -g -Werror -Wall -Wextra -Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -Wno-implicit-fallthrough -Wno-sign-compare -Wno-unused-parameter -I/home/bloink/Work/unnamedlinuxdistro/linux/tools/include -I/home/bloink/Work/unnamedlinuxdistro/linux/tools/include/uapi -I/home/bloink/Work/unnamedlinuxdistro/linux/tools/arch/x86/include/uapi -I/home/bloink/Work/unnamedlinuxdistro/linux/tools/arch/x86/include -I/home/bloink/Work/unnamedlinuxdistro/linux/tools/objtool/include -I/home/bloink/Work/unnamedlinuxdistro/linux/tools/objtool/arch/x86/include -I/home/bloink/Work/unnamedlinuxdistro/linux/tools/lib -DBUILD_KLP -DDISAS -DPACKAGE='objtool' -DDISASM_INIT_STYLED -D"BUILD_STR(s)=$(pound)s" -c -o /home/bloink/Work/unnamedlinuxdistro/linux/tools/objtool/libstring.o ../lib/string.c

source_/home/bloink/Work/unnamedlinuxdistro/linux/tools/objtool/libstring.o := ../lib/string.c

deps_/home/bloink/Work/unnamedlinuxdistro/linux/tools/objtool/libstring.o := \
  /usr/include/stdc-predef.h \
  /usr/include/stdlib.h \
  /usr/include/bits/libc-header-start.h \
  /usr/include/features.h \
  /usr/include/features-time64.h \
  /usr/include/bits/wordsize.h \
  /usr/include/bits/timesize.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/long-double.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/15/include/stddef.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/bits/floatn.h \
  /usr/include/bits/floatn-common.h \
  /usr/include/sys/types.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/bits/time64.h \
  /usr/include/bits/types/clock_t.h \
  /usr/include/bits/types/clockid_t.h \
  /usr/include/bits/types/time_t.h \
  /usr/include/bits/types/timer_t.h \
  /usr/include/bits/stdint-intn.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/endianness.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/uintn-identity.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/types/sigset_t.h \
  /usr/include/bits/types/__sigset_t.h \
  /usr/include/bits/types/struct_timeval.h \
  /usr/include/bits/types/struct_timespec.h \
  /usr/include/bits/select2.h \
  /usr/include/bits/select-decl.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/bits/thread-shared-types.h \
  /usr/include/bits/pthreadtypes-arch.h \
  /usr/include/bits/atomic_wide_counter.h \
  /usr/include/bits/struct_mutex.h \
  /usr/include/bits/struct_rwlock.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-bsearch.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/bits/stdlib.h \
  /usr/include/string.h \
  /usr/include/bits/types/locale_t.h \
  /usr/include/bits/types/__locale_t.h \
  /usr/include/strings.h \
  /usr/include/bits/strings_fortified.h \
  /usr/include/bits/string_fortified.h \
  /usr/include/errno.h \
  /usr/include/bits/errno.h \
  /usr/include/linux/errno.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/include/uapi/asm/errno.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/arch/x86/include/uapi/asm/errno.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/include/uapi/asm-generic/errno.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/include/uapi/asm-generic/errno-base.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/include/linux/string.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/15/include/stdbool.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/15/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/wchar.h \
  /usr/include/bits/stdint-uintn.h \
  /usr/include/bits/stdint-least.h \
  /usr/include/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/include/uapi/asm/bitsperlong.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/include/asm-generic/bitsperlong.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/include/linux/ctype.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/include/linux/compiler.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/include/linux/compiler_types.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/include/linux/compiler-context-analysis.h \
  /home/bloink/Work/unnamedlinuxdistro/linux/tools/include/linux/compiler-gcc.h \

/home/bloink/Work/unnamedlinuxdistro/linux/tools/objtool/libstring.o: $(deps_/home/bloink/Work/unnamedlinuxdistro/linux/tools/objtool/libstring.o)

$(deps_/home/bloink/Work/unnamedlinuxdistro/linux/tools/objtool/libstring.o):
