cmd_/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/objtool.o := gcc -Wp,-MD,/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/.objtool.o.d -Wp,-MT,/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/objtool.o -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wno-type-limits -Wstrict-aliasing=3 -Wshadow -Wno-switch-default -Wno-switch-enum -Wno-packed -Wno-nested-externs -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I ./scripts/include -g -I/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include -I/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/arch/x86/include/uapi -I/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/arch/x86/include -I/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/include -I/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/arch/x86/include -I/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/libsubcmd/include -D"BUILD_STR(s)=$(pound)s" -c -o /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/objtool.o objtool.c

source_/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/objtool.o := objtool.c

deps_/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/objtool.o := \
  /usr/include/stdc-predef.h \
  /usr/include/stdio.h \
  /usr/include/features.h \
  /usr/include/bits/alltypes.h \
  /usr/include/stdbool.h \
  /usr/include/string.h \
  /usr/include/strings.h \
  /usr/include/stdlib.h \
  /usr/include/alloca.h \
  /usr/include/unistd.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/libsubcmd/include/subcmd/exec-cmd.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/libsubcmd/include/subcmd/pager.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/kernel.h \
  /usr/include/stdarg.h \
  /usr/include/stddef.h \
  /usr/include/assert.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/build_bug.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/compiler.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/compiler_types.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/compiler-gcc.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/types.h \
  /usr/include/stdint.h \
  /usr/include/bits/stdint.h \
  /usr/include/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/asm-generic/bitsperlong.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/math.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/panic.h \
  /usr/include/endian.h \
  /usr/include/byteswap.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/include/objtool/builtin.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/libsubcmd/include/subcmd/parse-options.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/include/objtool/objtool.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/list.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/poison.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/hashtable.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/bitops.h \
  /usr/include/limits.h \
  /usr/include/bits/limits.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/bits.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/const.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/vdso/const.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/uapi/linux/const.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/vdso/bits.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/uapi/linux/bits.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/asm-generic/bitops.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/asm-generic/bitops/__ffs.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/asm-generic/bitops/__ffz.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/asm-generic/bitops/fls.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/asm-generic/bitops/__fls.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/asm-generic/bitops/fls64.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/asm-generic/bitops/hweight.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/asm-generic/bitops/arch_hweight.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/asm-generic/bitops/const_hweight.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/asm-generic/bitops/atomic.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/asm-generic/bitops/non-atomic.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/hash.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/log2.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/include/objtool/elf.h \
  /usr/include/gelf.h \
  /usr/include/libelf.h \
  /usr/include/sys/types.h \
  /usr/include/sys/select.h \
  /usr/include/elf.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/rbtree.h \
  /usr/include/linux/stddef.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/jhash.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/include/linux/unaligned/packed_struct.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/arch/x86/include/arch/elf.h \
  /home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/include/objtool/warn.h \
  /usr/include/sys/stat.h \
  /usr/include/bits/stat.h \
  /usr/include/fcntl.h \
  /usr/include/bits/fcntl.h \

/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/objtool.o: $(deps_/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/objtool.o)

$(deps_/home/sonakrie/Work/unnamedlinuxdistro/linux/tools/objtool/objtool.o):
