/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/bloink/Work/unnamedlinuxdistro/fs"
#define EXEC_PREFIX "/home/bloink/Work/unnamedlinuxdistro/fs"
#define BINDIR "/home/bloink/Work/unnamedlinuxdistro/fs/bin"
#define SBINDIR "/home/bloink/Work/unnamedlinuxdistro/fs/sbin"
#define LIBEXECDIR "/home/bloink/Work/unnamedlinuxdistro/fs/libexec"
#define DATAROOTDIR "/home/bloink/Work/unnamedlinuxdistro/fs/share"
#define DATADIR "/home/bloink/Work/unnamedlinuxdistro/fs/share"
#define SYSCONFDIR "/home/bloink/Work/unnamedlinuxdistro/fs/etc"
#define SHAREDSTATEDIR "/home/bloink/Work/unnamedlinuxdistro/fs/com"
#define LOCALSTATEDIR "/home/bloink/Work/unnamedlinuxdistro/fs/var"
#define RUNSTATEDIR "/home/bloink/Work/unnamedlinuxdistro/fs/var/run"
#define INCLUDEDIR "/home/bloink/Work/unnamedlinuxdistro/fs/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/bloink/Work/unnamedlinuxdistro/fs/share/doc/m4"
#define INFODIR "/home/bloink/Work/unnamedlinuxdistro/fs/share/info"
#define HTMLDIR "/home/bloink/Work/unnamedlinuxdistro/fs/share/doc/m4"
#define DVIDIR "/home/bloink/Work/unnamedlinuxdistro/fs/share/doc/m4"
#define PDFDIR "/home/bloink/Work/unnamedlinuxdistro/fs/share/doc/m4"
#define PSDIR "/home/bloink/Work/unnamedlinuxdistro/fs/share/doc/m4"
#define LIBDIR "/home/bloink/Work/unnamedlinuxdistro/fs/lib"
#define LISPDIR "/home/bloink/Work/unnamedlinuxdistro/fs/share/emacs/site-lisp"
#define LOCALEDIR "/home/bloink/Work/unnamedlinuxdistro/fs/share/locale"
#define MANDIR "/home/bloink/Work/unnamedlinuxdistro/fs/share/man"
#define PKGDATADIR "/home/bloink/Work/unnamedlinuxdistro/fs/share/m4"
#define PKGINCLUDEDIR "/home/bloink/Work/unnamedlinuxdistro/fs/include/m4"
#define PKGLIBDIR "/home/bloink/Work/unnamedlinuxdistro/fs/lib/m4"
#define PKGLIBEXECDIR "/home/bloink/Work/unnamedlinuxdistro/fs/libexec/m4"
