#!/bin/sh
case "$1" in
    deconfig)
        ip addr flush dev "$interface"
        ;;
    bound|renew)
        ip addr flush dev "$interface"
        ip addr add "$ip"/"$mask" dev "$interface"
        [ -n "$router" ] && ip route add default via "${router%% *}" dev "$interface"
        if [ -n "$dns" ]; then
            echo -n > /etc/resolv.conf
            for d in $dns; do
                echo "nameserver $d" >> /etc/resolv.conf
            done
        fi
        ;;
esac
exit 0
